
server:
  port: 9000
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      setting:
        web-allow-others: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:h2-northwind
    username: sa
    password: mypass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
