server:
  port: 9000
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-admin-password: adminpass
        web-allow-others: false
  datasource:
    driverClassName: org.h2.Driver
    # `DB_CLOSE_DELAY=-1` 参考 http://www.h2database.com/html/features.html#in_memory_databases
    # `DB_CLOSE_ON_EXIT=FALSE` 参考 https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.sql.datasource.embedded
    url: jdbc:h2:mem:h2-northwind;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: mypass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      # naming:
      # physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      # implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        "[format_sql]": true
        "[globally_quoted_identifiers]": false
        "[generate_statistics]": false
  sql:
    init:
      mode: always
      encoding: utf8
      schema-locations: classpath:db/schema-h2.sql
      # data-locations: classpath:db/data-h2.sql
  graphql:
    path: /graphql
    schema:
      locations: classpath:graphql/
      fileExtensions: .graphqls, .gqls
      printer:
        enabled: false
    graphiql:
      enabled: true
      path: /graphiql
